### ISSUE TITLE
[1.x] elemMatch: this.elem is undefined

### ISSUE THREAD

**Issue by blond** [bem/bem-xjst#100]
**Versions:**

* `enb-bemxjst`: `2.0.1`
* `bem-xjst`: `1.2.1`

**Template:**

```js
elemMatch(function() { return this.elem.indexOf('inner') === 0; }).content()(function() {
    return [
        { elem : 'label', content : this.elem.slice(-1) },
        this.ctx.content
    ];
})
```

After build of BEMHTML bundle in production mode and call `BEMHTML.apply()` is the error:

```
TypeError: Cannot read property 'indexOf' of undefined
    at BEMContext.<anonymous> (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:121:33)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:122:15)
    at __$b32 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:636:21)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:177:20)
    at __$b40 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:738:5)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:202:20)
    at __$b32 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:653:25)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:177:20)
    at __$b40 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:738:5)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:202:20)
```

More see in `bem-core`: https://github.com/bem/bem-core/issues/1181

**Comment by arikon** [comment]
Will not be fixed in favor of `bem-xjst@4.x`.

`bem-xjst@4.x` will be checked here https://github.com/bem/bem-xjst/issues/109.
