### ISSUE TITLE
Compiled template fails on require

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#52]
In `2.x` branch `require('./desktop.bundles/index/index.bemhtml.js');` results in 
```
ReferenceError: BEMHTML is not defined
    at __bem_xjst (/Users/tadatuta/Sites/rimarcom-base-xjst2/desktop.bundles/index/index.bemhtml.js:1339:15)
    at /Users/tadatuta/Sites/rimarcom-base-xjst2/desktop.bundles/index/index.bemhtml.js:1355:26
    at Object.<anonymous> (/Users/tadatuta/Sites/rimarcom-base-xjst2/desktop.bundles/index/index.bemhtml.js:1365:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
```
but `vm.runInContext()` works.

**Comment by indutny** [comment]
Fixed in 04666ca, thank you!
